### ISSUE TITLE
Android 12 beta2 报错，更改build.gradle解决

### ISSUE THREAD

**Issue by xukongyang** [artbits/android-mail#14]
Android 12 beta2 中运行报错，更改build.gradle解决

implementation 'com.sun.mail:android-mail:1.6.2'    
implementation 'com.sun.mail:android-activation:1.6.2'

更改为 

implementation 'com.sun.mail:android-mail:1.6.6'    
implementation 'com.sun.mail:android-activation:1.6.6'

**Comment by artbits** [comment]
已更新
