### ISSUE TITLE
无法发送outlook邮箱的邮件

### ISSUE THREAD

**Issue by ToSeeAll** [artbits/android-mail#16]
如题，好像是因为outlook的加密协议是STARTTLS，可参考：https://blog.csdn.net/m0_37897662/article/details/118307025
但是我不会，请问大佬可以修复下嘛

**Comment by artbits** [comment]
已新增对Outlook STARTTLS支持，详见 [Tools.java](https://github.com/artbits/android-mail/blob/master/mailkit/src/main/java/com/github/artbit/mailkit/Tools.java)
