### ISSUE TITLE
可否添加回对pop3协议的支持？另外对exchange支持好加吗？

### ISSUE THREAD

**Issue by xiaoluqiaoba** [artbits/android-mail#18]
本框架可否添加回对pop3协议的支持？
另外在此项目中添加对exchange的支持容易吗？
谢谢~

**Comment by artbits** [comment]
本项目仅支持协议SMTP和IMAP。因现在作者时间和精力有限，所以不计划长期维护它了，本次更新只是优化以前不成熟的代码，望见凉。
