### ISSUE TITLE
关于重构后的问题

### ISSUE THREAD

**Issue by leeprince0621** [artbits/android-mail#19]
新年快乐，新版本重构后和之前旧版本差别有点大，我想了解一下新版本有优化什么功能吗？之前使用的时候发现第一次拉取邮件比较慢，尤其是邮箱里有未读邮件。

**Comment by artbits** [comment]
新年快乐！重构只是重写以前代码，不再过度设计，并没有新增功能。项目也不再提供独立的库，而是整体作为邮箱项目开源。拉取邮件慢的问题，项目内部已经使用算法优化了这个问题，但是耗时主要在Javamail网络请求上，我也束手无策。
