### ISSUE TITLE
下一版本待开发的功能大概是...

### ISSUE THREAD

**Issue by artbits** [artbits/android-mail#9]
邮件的回复功能与转发功能。

晚安！2020.01.12 凌晨1:55

**Comment by yuxuan965960** [comment]
非常 nice

**Comment by GodFan4** [comment]
有没有考虑可以添加多个附件

**Comment by mailhu** [comment]
OK，可以。😀
发自我的QQ邮箱



---原始邮件---
发件人: &quot;GodFan4&quot;<notifications@github.com&gt;
发送时间: 2020年5月6日(周三) 上午9:47
收件人: &quot;mailhu/emailkit&quot;<emailkit@noreply.github.com&gt;;
抄送: &quot;湖湖&quot;<zguanhu@foxmail.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [mailhu/emailkit] 下一版本待开发的功能大概是... (#9)




 
有没有考虑可以添加多个附件
 
&mdash;

**Comment by artbits** [comment]
无法完成的下一版本，本次重构是最后的更新，结束了。
